In [1]:
import numpy as np

In [2]:
m1=np.array([[1,2],[3,4]])
print(m1)
m2=np.array([[2,3],[1,2]])
print(m2)
c=np.dot(m1,m2)
print(c)
t1=np.transpose(m1)
print(t1)
m3=m2.flatten()
print(m3)

[[1 2]
 [3 4]]
[[2 3]
 [1 2]]
[[ 4  7]
 [10 17]]
[[1 3]
 [2 4]]
[2 3 1 2]


In [3]:
m1=int(input("Enter num : "))

Enter num :  2


In [5]:
# read matrix from the user
mat=[]
for i in range(2):
    row=[]
    for j in range(2):
        a=int(input())
        row.append(a)
    mat.append(row)
print(mat)


 3
 2
 3
 4


[[3, 2], [3, 4]]


In [6]:
tr=np.transpose(mat)
print(tr)

[[3 3]
 [2 4]]


In [7]:
mat1=[]
r=int(input("Enter rows : "))
c=int(input("Enter cols: "))
for i in range(r):
    rows=[]
    for j in range(c):
        a=int(input())
        rows.append(a)
    mat1.append(rows)
for i in range (r):
    for j in range (c):
        print(mat1[i][j],end=" ")
    print(" ")

Enter rows :  2
Enter cols:  3
 1
 2
 3
 4
 4
 5


1 2 3  
4 4 5  


In [9]:
# get row size and col size from user for creating matrix using list function
a=list(map(int,input().split()))

matrix=np.array(a).reshape(2,2)
print(matrix)

 1 2 3 4


[[1 2]
 [3 4]]


In [10]:
# create a vector with value from 0-20 and change the sign of the number in the range from 9-15
# write a numpy prgrm to compute sum of all elmnts,each cols,each rows of given array
# write a numpy prgrm  to save a text file and load it
# write a numpy program to check whether 2 arrays are eaqual or not (elmnt wise comparison)
# create 4*4 array with ranom values , create a new array from the set array by swapping 1st and last rows
# numpy prgrm to multiply two given arrays of same size elemnt by elemnt

In [11]:
# create a vector with value from 0-20 and change the sign of the number in the range from 9-15
vectors=np.arange(21)
print(vectors)
vectors[(vectors>=9)&(vectors<=15)]*=-1
print(vectors)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [15]:
print(m2)

[[2 3]
 [1 2]]


In [16]:
# transpose,rank,inverse,trace,eigenvalues
# rank
rank=np.linalg.matrix_rank(m2)
print(rank)

2


In [17]:
# transpose
transpos=np.transpose(m2)
print(transpos)

[[2 1]
 [3 2]]


In [19]:
# inverse
inverse=np.linalg.inv(m2)
print(inverse)

[[ 2. -3.]
 [-1.  2.]]


In [20]:
# trace 
tr=np.trace(m2)
print(tr)

4


In [24]:
# eigenvalues
e1,e2=np.linalg.eig(m2)
print("eigen values: ",e1)
print("Eigen vectors : \n",e2)

eigen values:  [3.73205081 0.26794919]
Eigen vectors : 
 [[ 0.8660254 -0.8660254]
 [ 0.5        0.5      ]]


In [29]:
# write a numpy prgrm to compute sum of all elmnts,each cols,each rows of given array
array=np.array([[1,2,3],
       [2,3,4],
       [3,3,3]])
print(array)
total_sum=np.sum(array)
print("Total Sum : ",total_sum)
col_sum=np.sum(array,axis=0)
print("Column wise sum : ",col_sum)
row_sum=np.sum(array,axis=1)
print("Row wise sum : ",row_sum)

[[1 2 3]
 [2 3 4]
 [3 3 3]]
Total Sum :  24
Column wise sum :  [ 6  8 10]
Row wise sum :  [6 9 9]


In [32]:
m1=np.array([[1,2,3],
            [4,5,6]])
m2=np.array([[1,2,3],
            [4,9,6]])
comp=m1==m2
print(comp)

[[ True  True  True]
 [ True False  True]]


In [35]:
# create 4*4 array with ranom values , create a new array from the set array by swapping 1st and last rows
o_array=np.random.randint(0,100,size=(4,4))
print("Original array \n",o_array)
n_array=np.copy(o_array)
n_array[[0,-1]]=n_array[[-1,0]]
print("New array\n",n_array)

Original array 
 [[29  6 76 46]
 [25 44 29 36]
 [75  9  3  8]
 [23 82 23 36]]
New array
 [[23 82 23 36]
 [25 44 29 36]
 [75  9  3  8]
 [29  6 76 46]]


In [38]:
print("First array\n",m1)
print("Second array\n",m2)
pro=m1*m2
print("Element wise product \n",pro)

First array
 [[1 2 3]
 [4 5 6]]
Second array
 [[1 2 3]
 [4 9 6]]
Element wise product 
 [[ 1  4  9]
 [16 45 36]]


In [41]:
# write a numpy prgrm  to save a text file and load it
print(array,"\n")
fname="array1.txt"
np.savetxt(fname,array)
lod=np.loadtxt(fname)
print(lod)

[[1 2 3]
 [2 3 4]
 [3 3 3]] 

[[1. 2. 3.]
 [2. 3. 4.]
 [3. 3. 3.]]


In [ ]:
# Write a python prgrm to create a bar plot of scores by group and gender.Use multiple X values on the same chart for men and women.
men=[22,30,35,35,26]
women=[25,32,30,35,29]